### ISSUE TITLE
Fails if numbers are used as keys

### ISSUE THREAD

**Issue by KOLANICH** [dpranke/pyjson5#13]
```javascript
{1:2}
```

**Comment by Eliont** [comment]
How to worka around this:

        numeric_keys = list(set(re.findall('[{,\,][0-9]+:?',f))
        for entry in numeric_keys:
            replacement = entry[0] + '"' + entry[1:-1] + '"' + entry[-1]  
            f = f.replace(entry,replacement)

then do json5.loads

**Comment by KOLANICH** [comment]
It's a bad workaround. It's better to try parse every number in keys IMHO. But much better is to fix the lib.

**Comment by dpranke** [comment]
While it's legal in Javascript to use numbers as keys (because they implicitly get converted to strings), it's not legal to do so in either JSON (where all keys must be double-quoted strings) or in JSON-5 (which allows identifiers, but nothing else, see https://github.com/json5/json5 ).

So, I think it'd probably be wrong to support them here.
