### ISSUE TITLE
Update pyjson5 grammar to JSON5 official ABNF??? 

### ISSUE THREAD

**Issue by cavanaug** [dpranke/pyjson5#15]
There is now an official ABNF grammar for json5.  Could the pyjson5 grammar be updated to use this??

I think this might fix some of the parsing errors (negative numbers, unicode chars etc).     Id try to fix it myself but Im not too familar with the glop stuff.

See:  https://github.com/json5/json5-spec/blob/master/json5.abnf

**Comment by dpranke** [comment]
Thanks for the pointer, I hadn't seen that. 

pyjson5 is implemented using a parser generated from a parsing expression grammar, so I can't easily just switch to the file as-is (or, at least, I wouldn't want to).

However, it's a good reference, and I can  certainly try to conform to it.

I know the code hasn't been updated for a long time :(. It's not because it's hard to do so, but I've just had to worry about other things. However, I'm actually planning to make some real time for this in the next couple days, so hopefully I can fix a bunch of these issues.

**Comment by cavanaug** [comment]
Great!!  I look forward to the changes and fixes!!

**Comment by cavanaug** [comment]
Hey, I dont mean to pester you, but we have been sort of holding off doing some work in anticipation of your updates.   Any chance this will be updated soon??

**Comment by dpranke** [comment]
Sorry for the delay! I've been distracted by work on the underlying parser generator, but I will try to undistract myself and get *something* out later today.

**Comment by dpranke** [comment]
Things should be substantially better in the latest commit, 3cb64842, which I've tagged with `v0.3`. I will do another release to PyPI once I've done a bit more testing and fixed a couple more issues, hopefully in a couple days.

I haven't actually done a strict comparison against the ABNF file yet. I plan to do that and also port over the tests that are run against the JS implementation.

**Comment by cavanaug** [comment]
I installed and used it today.   Looks *much* better, it is now in a functional state for us.   Thanks!!

**Comment by dpranke** [comment]
Great, I'm glad to hear it. I'll try to get the remaining issues ironed out and a package published today.

**Comment by dpranke** [comment]
I've added support for unicode identifiers, and done a bunch more testing. I've published the latest version as v0.4.0. Hopefully this works for you :).
