### ISSUE TITLE
Omit quotes for the keys while dumping JSON5 string

### ISSUE THREAD

**Issue by drom** [dpranke/pyjson5#22]
When dumping JSON5 file, could you omit quotes around the object keys?
It makes it more readable IMHO

**Comment by dpranke** [comment]
Yes, we could certainly do that. I don't remember offhand a reason why I specifically didn't, apart from probably just being lazy :). It's probably only a couple-line patch to lib.py.

**Comment by dpranke** [comment]
So, it turns out that I did implement this, but I had forgotten about it, and I implemented it in a way that now seems kinda wrong.

json5.dump() and json5.dumps() support "compact" and "as_json" keywords, and "compact" is False by default. If compact is False, or as_json is True, then json5.dump() and json5.dumps() just call out to json.dump() and json.dumps(), respectively. I suppose I probably did this for compatibility.

This means that if you actually want to omit the quotes, you have to call `dump(obj, compact=True)`.

In retrospect this seems silly though; if you want json-compatible output, use json.dumps(). If you're calling json5.dumps(), you probably really want json5-compatible output.

I'll work on fixing this on master, and turn this into a new v0.7 release (since it'll be slightly incompatible). I may actually also fully implement the other keywords directly for dump() and dumps(), so that the library can be properly standalone and not depend on json at all.

**Comment by dpranke** [comment]
Okay, this should be fixed in v0.7.0 (97f83f4300dd2a9f3c5068b74b7a139a6a5a3318) , which I've just pushed to PyPI
