### ISSUE TITLE
Load to object instead of class

### ISSUE THREAD

**Issue by silas2471** [dpranke/pyjson5#45]
Hey, 
within the JSON5 Format one can use ObjectKeys, which are not quoted/strings.
Is it possible to load those json files straight to an object, instead of a dict?
This would make accessing and using the data much more convenient, especially if one has a file with many levels.
It should also enable autocompletion in many Editors (if a dummyObject with the same structure as the file is given).
An example is given below:
```
//dummyFile
{
    config1: {
        dummy1:1,
        dummy2:2
    },
    config2:{
        dummy2:3
    }
}
.....
//Accessing files and converting to object.
with open(dummyFile, "r") as fob:
    data = json5.load(fob)
    
var1 = data.config1.dummy1             // loading and accessing the data as object
var2 = data["config1"]["dummy1"]       // loading and accessing data as a dict (currently)
```

**Comment by dpranke** [comment]
Thanks for the suggestion.

You should be able to achieve that easily enough using the `object_hook` or `object_pairs_hook` arguments to `json5.load()`.

I would be a little reluctant to implement that directly in the library because I'm not entirely sure what all interfaces users would want the objects to implement (nothing? Everything `dict` implements? etc.). 

If there was a consensus from a bunch of users I'd probably be more open to implementing something, but you're the first person to ask for this.

(Of course, there's no discussion list for this library, either, so no real way to ask other users for opinions, either ...)

As to enabling autocompletion in editors, I'm not actually sure how that would work for generic objects ... If you had a pointer describing what might be needed, I'd be interested in learning more.

How does that sound?

**Comment by silas2471** [comment]
Hey,
I figured out a way to make it work using munchify. 
Unfortunately I had to abandon using json5 as a config file, as is does not support keeping comments using json5.dump() .
Now I am using .py files as config.

Regarding autocompletion, I am using a "DefaultConfig" in a python class, which has the same structure/attributes as the previously used munchified Json5 config ().
```
def func(config: DefaultConfig):
     pass # now autocompletion regarding the structure of DefaultConfig is available.
```
Thanks for your ideas though :)

**Comment by dpranke** [comment]
Thanks. 

How are you solving this problem using python files for configuration? Are you using some library that'll preserve comments, or are you rolling your own logic?

[ Preserving comments in pyjson5 is issue #28 ]

Implementing everything `dict` does does seem like a reasonable default behavior.

Using a default object as a parameter type makes sense, but I'm not sure how that'd work when trying to
refer to a config file.

I'll leave this open in case others have similar requests in the future.

[ Note to self for future reference: [munch](https://github.com/Infinidat/munch) (munchify is part of that). ]

**Comment by silas2471** [comment]
Uhm I am displaying the .py files using the normal open and .readlines() / .writlines() Operator. In order to retrieve the config, I use the builtin runpy.run_path() function to retrieve the class.  In my case all config files have the same structure, just different attributes.
Thus I can use the default config as parameter type, and the passed config, retrieved from runpy.run_path can be accessed with the autocompletion.

**Comment by dpranke** [comment]
Gotcha.

**Comment by dpranke** [comment]
Closing as the user found a workaround
